[input]
base_directory = "output"
html_selector = "main"

[[input.files]]
path = "pages/about-me.html"
url = "/pages/about-me.html"
title = "About me"

[[input.files]]
path = "pages/ai-art.html"
url = "/pages/ai-art.html"
title = "AI art"

[[input.files]]
path = "pages/crypto.html"
url = "/pages/crypto.html"
title = "Crypto"

[[input.files]]
path = "pages/data-science.html"
url = "/pages/data-science.html"
title = "Data Science"

[[input.files]]
path = "pages/manga-anime.html"
url = "/pages/manga-anime.html"
title = "Manga & Anime"

[[input.files]]
path = "pages/media-appearances.html"
url = "/pages/media-appearances.html"
title = "Media Appearances"

[[input.files]]
path = "pages/music.html"
url = "/pages/music.html"
title = "Music"

[[input.files]]
path = "japan-as-an-international-hub-for-ai.html"
url = "/japan-as-an-international-hub-for-ai.html"
title = "Japan as an international hub for AI"

[[input.files]]
path = "why-creativity-flourishes-in-japan.html"
url = "/why-creativity-flourishes-in-japan.html"
title = "Why creativity flourishes in Japan"

[[input.files]]
path = "trying-out-ai-music-generation-with-dance-diffusion.html"
url = "/trying-out-ai-music-generation-with-dance-diffusion.html"
title = "Trying out AI music generation with Dance Diffusion"

[[input.files]]
path = "positive-trends-in-japan.html"
url = "/positive-trends-in-japan.html"
title = "Positive trends in Japan"

[[input.files]]
path = "my-2001-stanford-application-essay-on-algorithmic-music.html"
url = "/my-2001-stanford-application-essay-on-algorithmic-music.html"
title = "My 2001 Stanford application essay on algorithmic music"

[[input.files]]
path = "how-stable-diffusion-latent-diffusion-works.html"
url = "/how-stable-diffusion-latent-diffusion-works.html"
title = "How Stable Diffusion (Latent Diffusion) works"

[[input.files]]
path = "easy-blog-migration-from-medium-to-your-own-site-using-python.html"
url = "/easy-blog-migration-from-medium-to-your-own-site-using-python.html"
title = "Easy Blog Migration From Medium To Your Own Site Using Python"

[[input.files]]
path = "how-machine-learning-may-save-humanity.html"
url = "/how-machine-learning-may-save-humanity.html"
title = "How Machine Learning May Save Humanity"

[[input.files]]
path = "the-nature-of-human-intelligence-from-a-computer-science-perspective.html"
url = "/the-nature-of-human-intelligence-from-a-computer-science-perspective.html"
title = "The Nature Of Human Intelligence From A Computer Science Perspective"

[[input.files]]
path = "guide-to-working-with-me-a-data-science-manager.html"
url = "/guide-to-working-with-me-a-data-science-manager.html"
title = "Guide To Working With Me A Data Science Manager"

[[input.files]]
path = "how-to-be-an-awesome-data-science-manager.html"
url = "/how-to-be-an-awesome-data-science-manager.html"
title = "How To Be An Awesome Data Science Manager"

[[input.files]]
path = "how-to-be-an-awesome-data-scientist.html"
url = "/how-to-be-an-awesome-data-scientist.html"
title = "How To Be An Awesome Data Scientist"

[[input.files]]
path = "generating-fake-k-pop-faces-part-1.html"
url = "/generating-fake-k-pop-faces-part-1.html"
title = "Generating Fake K-pop Faces Part 1"

[[input.files]]
path = "my-favorite-mind-blowing-mlai-breakthroughs.html"
url = "/my-favorite-mind-blowing-mlai-breakthroughs.html"
title = "My Favorite Mind Blowing ML/AI Breakthroughs"

[[input.files]]
path = "thoughts-on-my-past-2018-and-future-2019.html"
url = "/thoughts-on-my-past-2018-and-future-2019.html"
title = "Thoughts On My Past 2018 And Future 2019"